services:
  GepurIt\OneCClientBundle\HttpClient\ApiHttpClient:
    class: GepurIt\OneCClientBundle\HttpClient\ApiHttpClient
    autowire: true

  GepurIt\OneCClientBundle\Rabbit\:
    resource: '../../Rabbit'
    autowire: true

  GepurIt\OneCClientBundle\Command\:
    resource: '../../Command'
    autowire: true
    tags:
      - { name: console.command }

  GepurIt\OneCClientBundle\DeferredRequest\ErrorHandler\DeferredRequestErrorHandler:
    autowire: true

  GepurIt\OneCClientBundle\DeferredRequestErrorHandler\ResendRequest:
    autowire: true
    tags:
      - {name: one_c.dr_error.handler, priority: 500}

  GepurIt\OneCClientBundle\Security\HashGenerator:
    autowire: true